---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS config deployment to alert and auto-remediate security groups that contain open rules via ports 22 and 3389'

Parameters:

  EmailAddress2:
    Type: String
    Default: ''

Resources:

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SNS-Topic-For-Block-Open-SG-Alerts

  EmailSubscription2:
    DependsOn: SNSTopic
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref SNSTopic
      Endpoint: !Ref EmailAddress2

  ConfigRoleBlockOpenSG:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: ConfigRoleBlockOpenSG
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: SecurityGroupPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:*'
                Resource: '*'
        - PolicyName: SSMPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:*'
                Resource: '*'

  ConfigRuleBlockOpenSG:
    Type: 'AWS::Config::ConfigRule'
    Properties:
      ConfigRuleName: Block-Open-SSH-RDP
      Description: >-
        Checks whether the security group of EC2 instances allows unrestricted
        incoming TCP traffic to the specified ports.
      Scope:
        ComplianceResourceTypes:
          - 'AWS::EC2::SecurityGroup'
      Source:
        Owner: AWS
        SourceIdentifier: RESTRICTED_INCOMING_TRAFFIC
      InputParameters:
        blockedPort1: '22'
        blockedPort2: '3389'

  RemediationConfigurations:
    Type: 'AWS::Config::RemediationConfiguration'
    Properties:
      ConfigRuleName: !Ref ConfigRuleBlockOpenSG
      TargetType: SSM_DOCUMENT
      TargetId: AWS-DisablePublicAccessForSecurityGroup
      TargetVersion: $LATEST
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - !GetAtt ConfigRoleBlockOpenSG.Arn
        GroupId:
          ResourceValue:
            Value: "RESOURCE_ID"
      ResourceType: 'AWS::EC2::SecurityGroup'
      Automatic: true
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 60

  ConfigRuleCloudWatchEvent:
    Type: AWS::Events::Rule
    DependsOn: SNSTopic
    Properties:
      Description: CloudWatch Events rule to trigger AWS Config rule evaluation.
      EventPattern:
        source:
          - aws.config
        detail-type:
          - Config Rules Compliance Change
        detail:
          messageType:
            - ComplianceChangeNotification
          configRuleName:
            - !Ref ConfigRuleBlockOpenSG
      State: ENABLED
      Targets:
        - Arn: !Ref SNSTopic
          Id: "TargetSNSTopic"
          InputTransformer:
            InputPathsMap:
              "awsRegion": "$.detail.awsRegion"
              "complianceType": "$.detail.newEvaluationResult.complianceType"
              "resourceId": "$.detail.resourceId"
            InputTemplate: |
              "The resource <resourceId> in region <awsRegion> had an inbound rule open to internet for port 22/3389 and is being automatically removed as per security guidelines"
